package com.ponani.hourly.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.*

/**
 * Details the structure of a row in a table and provides table name
 * Time might be autogenerated or will need to filled out manually
 * Category details if leisure work exercise etc in a string
 */
@Entity(tableName = "HourlyTable")
class HourlyItem(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "hourly_id")
    var hourlyID: Int = 0,
    var hourlyTime: Date = Date(0),
    var hourlyCategory: Int = 0,
    var hourDetails: String = ""
) {
    constructor(_hourlyTime: Date, _hourlyCategory: Int,_hourlyString: String): this(){
        hourlyTime = _hourlyTime
        hourlyCategory = _hourlyCategory
        hourDetails = _hourlyString
    }
}